# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='',
  serialized_pb=_b('\n\rpayload.proto\"<\n\rSignedPayload\x12\x1d\n\x15serializedMessageData\x18\x01 \x02(\x0c\x12\x0c\n\x04HMac\x18\x02 \x02(\x0c\"\xbf\x01\n\x0bMessageData\x12\x11\n\tmessageID\x18\x01 \x02(\x0c\x12\x10\n\x08sequence\x18\x02 \x02(\x04\x12\x15\n\rsenderAddress\x18\x03 \x02(\t\x12\x13\n\x0bmessageType\x18\x04 \x01(\t\x12\x11\n\ttimeStamp\x18\x05 \x02(\x04\x12\x0f\n\x07subject\x18\x06 \x01(\t\x12\x1a\n\x12unencryptedMessage\x18\x07 \x02(\t\x12\x12\n\nsenderName\x18\x08 \x01(\t\x12\x0b\n\x03pad\x18\t \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIGNEDPAYLOAD = _descriptor.Descriptor(
  name='SignedPayload',
  full_name='SignedPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serializedMessageData', full_name='SignedPayload.serializedMessageData', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HMac', full_name='SignedPayload.HMac', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=77,
)


_MESSAGEDATA = _descriptor.Descriptor(
  name='MessageData',
  full_name='MessageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageID', full_name='MessageData.messageID', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='MessageData.sequence', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senderAddress', full_name='MessageData.senderAddress', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messageType', full_name='MessageData.messageType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='MessageData.timeStamp', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subject', full_name='MessageData.subject', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unencryptedMessage', full_name='MessageData.unencryptedMessage', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senderName', full_name='MessageData.senderName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pad', full_name='MessageData.pad', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=271,
)

DESCRIPTOR.message_types_by_name['SignedPayload'] = _SIGNEDPAYLOAD
DESCRIPTOR.message_types_by_name['MessageData'] = _MESSAGEDATA

SignedPayload = _reflection.GeneratedProtocolMessageType('SignedPayload', (_message.Message,), dict(
  DESCRIPTOR = _SIGNEDPAYLOAD,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:SignedPayload)
  ))
_sym_db.RegisterMessage(SignedPayload)

MessageData = _reflection.GeneratedProtocolMessageType('MessageData', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEDATA,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:MessageData)
  ))
_sym_db.RegisterMessage(MessageData)


# @@protoc_insertion_point(module_scope)
