#!/bin/bash

if [ $1 == "start" ] ; then
	echo "Subspace server starting..."
	sudo service mongod start
	twistd -noy server.py

else if [ $1 == "stop" ] ; then
	echo "Stopping subspace..."
	kill -INT `cat twistd.pid`
	sudo service mongod stop
     fi
fi
