// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyRing.proto

package Messenger;

public final class KeyRing {
  private KeyRing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SavedKeysOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Key key = 1;
    /**
     * <code>repeated .Key key = 1;</code>
     */
    java.util.List<KeyRing.Key> 
        getKeyList();
    /**
     * <code>repeated .Key key = 1;</code>
     */
    KeyRing.Key getKey(int index);
    /**
     * <code>repeated .Key key = 1;</code>
     */
    int getKeyCount();
    /**
     * <code>repeated .Key key = 1;</code>
     */
    java.util.List<? extends KeyRing.KeyOrBuilder> 
        getKeyOrBuilderList();
    /**
     * <code>repeated .Key key = 1;</code>
     */
    KeyRing.KeyOrBuilder getKeyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SavedKeys}
   */
  public static final class SavedKeys extends
      com.google.protobuf.GeneratedMessage
      implements SavedKeysOrBuilder {
    // Use SavedKeys.newBuilder() to construct.
    private SavedKeys(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SavedKeys(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SavedKeys defaultInstance;
    public static SavedKeys getDefaultInstance() {
      return defaultInstance;
    }

    public SavedKeys getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SavedKeys(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                key_ = new java.util.ArrayList<KeyRing.Key>();
                mutable_bitField0_ |= 0x00000001;
              }
              key_.add(input.readMessage(KeyRing.Key.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          key_ = java.util.Collections.unmodifiableList(key_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KeyRing.internal_static_SavedKeys_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KeyRing.internal_static_SavedKeys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KeyRing.SavedKeys.class, KeyRing.SavedKeys.Builder.class);
    }

    public static com.google.protobuf.Parser<SavedKeys> PARSER =
        new com.google.protobuf.AbstractParser<SavedKeys>() {
      public SavedKeys parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SavedKeys(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SavedKeys> getParserForType() {
      return PARSER;
    }

    // repeated .Key key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.util.List<KeyRing.Key> key_;
    /**
     * <code>repeated .Key key = 1;</code>
     */
    public java.util.List<KeyRing.Key> getKeyList() {
      return key_;
    }
    /**
     * <code>repeated .Key key = 1;</code>
     */
    public java.util.List<? extends KeyRing.KeyOrBuilder> 
        getKeyOrBuilderList() {
      return key_;
    }
    /**
     * <code>repeated .Key key = 1;</code>
     */
    public int getKeyCount() {
      return key_.size();
    }
    /**
     * <code>repeated .Key key = 1;</code>
     */
    public KeyRing.Key getKey(int index) {
      return key_.get(index);
    }
    /**
     * <code>repeated .Key key = 1;</code>
     */
    public KeyRing.KeyOrBuilder getKeyOrBuilder(
        int index) {
      return key_.get(index);
    }

    private void initFields() {
      key_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getKeyCount(); i++) {
        if (!getKey(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < key_.size(); i++) {
        output.writeMessage(1, key_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < key_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, key_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static KeyRing.SavedKeys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KeyRing.SavedKeys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KeyRing.SavedKeys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KeyRing.SavedKeys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KeyRing.SavedKeys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static KeyRing.SavedKeys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static KeyRing.SavedKeys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static KeyRing.SavedKeys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static KeyRing.SavedKeys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static KeyRing.SavedKeys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(KeyRing.SavedKeys prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SavedKeys}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements KeyRing.SavedKeysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KeyRing.internal_static_SavedKeys_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KeyRing.internal_static_SavedKeys_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                KeyRing.SavedKeys.class, KeyRing.SavedKeys.Builder.class);
      }

      // Construct using KeyRing.SavedKeys.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKeyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (keyBuilder_ == null) {
          key_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          keyBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KeyRing.internal_static_SavedKeys_descriptor;
      }

      public KeyRing.SavedKeys getDefaultInstanceForType() {
        return KeyRing.SavedKeys.getDefaultInstance();
      }

      public KeyRing.SavedKeys build() {
        KeyRing.SavedKeys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public KeyRing.SavedKeys buildPartial() {
        KeyRing.SavedKeys result = new KeyRing.SavedKeys(this);
        int from_bitField0_ = bitField0_;
        if (keyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            key_ = java.util.Collections.unmodifiableList(key_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.key_ = key_;
        } else {
          result.key_ = keyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof KeyRing.SavedKeys) {
          return mergeFrom((KeyRing.SavedKeys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(KeyRing.SavedKeys other) {
        if (other == KeyRing.SavedKeys.getDefaultInstance()) return this;
        if (keyBuilder_ == null) {
          if (!other.key_.isEmpty()) {
            if (key_.isEmpty()) {
              key_ = other.key_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureKeyIsMutable();
              key_.addAll(other.key_);
            }
            onChanged();
          }
        } else {
          if (!other.key_.isEmpty()) {
            if (keyBuilder_.isEmpty()) {
              keyBuilder_.dispose();
              keyBuilder_ = null;
              key_ = other.key_;
              bitField0_ = (bitField0_ & ~0x00000001);
              keyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKeyFieldBuilder() : null;
            } else {
              keyBuilder_.addAllMessages(other.key_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getKeyCount(); i++) {
          if (!getKey(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        KeyRing.SavedKeys parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (KeyRing.SavedKeys) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Key key = 1;
      private java.util.List<KeyRing.Key> key_ =
        java.util.Collections.emptyList();
      private void ensureKeyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          key_ = new java.util.ArrayList<KeyRing.Key>(key_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          KeyRing.Key, KeyRing.Key.Builder, KeyRing.KeyOrBuilder> keyBuilder_;

      /**
       * <code>repeated .Key key = 1;</code>
       */
      public java.util.List<KeyRing.Key> getKeyList() {
        if (keyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(key_);
        } else {
          return keyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public int getKeyCount() {
        if (keyBuilder_ == null) {
          return key_.size();
        } else {
          return keyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public KeyRing.Key getKey(int index) {
        if (keyBuilder_ == null) {
          return key_.get(index);
        } else {
          return keyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder setKey(
          int index, KeyRing.Key value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyIsMutable();
          key_.set(index, value);
          onChanged();
        } else {
          keyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder setKey(
          int index, KeyRing.Key.Builder builderForValue) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          key_.set(index, builderForValue.build());
          onChanged();
        } else {
          keyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder addKey(KeyRing.Key value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyIsMutable();
          key_.add(value);
          onChanged();
        } else {
          keyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder addKey(
          int index, KeyRing.Key value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyIsMutable();
          key_.add(index, value);
          onChanged();
        } else {
          keyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder addKey(
          KeyRing.Key.Builder builderForValue) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          key_.add(builderForValue.build());
          onChanged();
        } else {
          keyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder addKey(
          int index, KeyRing.Key.Builder builderForValue) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          key_.add(index, builderForValue.build());
          onChanged();
        } else {
          keyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder addAllKey(
          java.lang.Iterable<? extends KeyRing.Key> values) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          super.addAll(values, key_);
          onChanged();
        } else {
          keyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder clearKey() {
        if (keyBuilder_ == null) {
          key_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          keyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public Builder removeKey(int index) {
        if (keyBuilder_ == null) {
          ensureKeyIsMutable();
          key_.remove(index);
          onChanged();
        } else {
          keyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public KeyRing.Key.Builder getKeyBuilder(
          int index) {
        return getKeyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public KeyRing.KeyOrBuilder getKeyOrBuilder(
          int index) {
        if (keyBuilder_ == null) {
          return key_.get(index);  } else {
          return keyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public java.util.List<? extends KeyRing.KeyOrBuilder> 
           getKeyOrBuilderList() {
        if (keyBuilder_ != null) {
          return keyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(key_);
        }
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public KeyRing.Key.Builder addKeyBuilder() {
        return getKeyFieldBuilder().addBuilder(
            KeyRing.Key.getDefaultInstance());
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public KeyRing.Key.Builder addKeyBuilder(
          int index) {
        return getKeyFieldBuilder().addBuilder(
            index, KeyRing.Key.getDefaultInstance());
      }
      /**
       * <code>repeated .Key key = 1;</code>
       */
      public java.util.List<KeyRing.Key.Builder> 
           getKeyBuilderList() {
        return getKeyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          KeyRing.Key, KeyRing.Key.Builder, KeyRing.KeyOrBuilder> 
          getKeyFieldBuilder() {
        if (keyBuilder_ == null) {
          keyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              KeyRing.Key, KeyRing.Key.Builder, KeyRing.KeyOrBuilder>(
                  key_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          key_ = null;
        }
        return keyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SavedKeys)
    }

    static {
      defaultInstance = new SavedKeys(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SavedKeys)
  }

  public interface KeyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes privateKey = 1;
    /**
     * <code>required bytes privateKey = 1;</code>
     */
    boolean hasPrivateKey();
    /**
     * <code>required bytes privateKey = 1;</code>
     */
    com.google.protobuf.ByteString getPrivateKey();

    // optional bytes publicKey = 2;
    /**
     * <code>optional bytes publicKey = 2;</code>
     */
    boolean hasPublicKey();
    /**
     * <code>optional bytes publicKey = 2;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    // required string name = 3;
    /**
     * <code>required string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 prefixLength = 4;
    /**
     * <code>required int32 prefixLength = 4;</code>
     */
    boolean hasPrefixLength();
    /**
     * <code>required int32 prefixLength = 4;</code>
     */
    int getPrefixLength();

    // optional string address = 5;
    /**
     * <code>optional string address = 5;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 5;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    // required string uploadNode = 6;
    /**
     * <code>required string uploadNode = 6;</code>
     */
    boolean hasUploadNode();
    /**
     * <code>required string uploadNode = 6;</code>
     */
    java.lang.String getUploadNode();
    /**
     * <code>required string uploadNode = 6;</code>
     */
    com.google.protobuf.ByteString
        getUploadNodeBytes();

    // required string timeOfLastGET = 7 [default = "0"];
    /**
     * <code>required string timeOfLastGET = 7 [default = "0"];</code>
     */
    boolean hasTimeOfLastGET();
    /**
     * <code>required string timeOfLastGET = 7 [default = "0"];</code>
     */
    java.lang.String getTimeOfLastGET();
    /**
     * <code>required string timeOfLastGET = 7 [default = "0"];</code>
     */
    com.google.protobuf.ByteString
        getTimeOfLastGETBytes();
  }
  /**
   * Protobuf type {@code Key}
   */
  public static final class Key extends
      com.google.protobuf.GeneratedMessage
      implements KeyOrBuilder {
    // Use Key.newBuilder() to construct.
    private Key(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Key(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Key defaultInstance;
    public static Key getDefaultInstance() {
      return defaultInstance;
    }

    public Key getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Key(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              privateKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              publicKey_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              prefixLength_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              address_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              uploadNode_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              timeOfLastGET_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KeyRing.internal_static_Key_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KeyRing.internal_static_Key_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KeyRing.Key.class, KeyRing.Key.Builder.class);
    }

    public static com.google.protobuf.Parser<Key> PARSER =
        new com.google.protobuf.AbstractParser<Key>() {
      public Key parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Key(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Key> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes privateKey = 1;
    public static final int PRIVATEKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <code>required bytes privateKey = 1;</code>
     */
    public boolean hasPrivateKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes privateKey = 1;</code>
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    // optional bytes publicKey = 2;
    public static final int PUBLICKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>optional bytes publicKey = 2;</code>
     */
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes publicKey = 2;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>required string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 prefixLength = 4;
    public static final int PREFIXLENGTH_FIELD_NUMBER = 4;
    private int prefixLength_;
    /**
     * <code>required int32 prefixLength = 4;</code>
     */
    public boolean hasPrefixLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 prefixLength = 4;</code>
     */
    public int getPrefixLength() {
      return prefixLength_;
    }

    // optional string address = 5;
    public static final int ADDRESS_FIELD_NUMBER = 5;
    private java.lang.Object address_;
    /**
     * <code>optional string address = 5;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string address = 5;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string uploadNode = 6;
    public static final int UPLOADNODE_FIELD_NUMBER = 6;
    private java.lang.Object uploadNode_;
    /**
     * <code>required string uploadNode = 6;</code>
     */
    public boolean hasUploadNode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string uploadNode = 6;</code>
     */
    public java.lang.String getUploadNode() {
      java.lang.Object ref = uploadNode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uploadNode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uploadNode = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUploadNodeBytes() {
      java.lang.Object ref = uploadNode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uploadNode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string timeOfLastGET = 7 [default = "0"];
    public static final int TIMEOFLASTGET_FIELD_NUMBER = 7;
    private java.lang.Object timeOfLastGET_;
    /**
     * <code>required string timeOfLastGET = 7 [default = "0"];</code>
     */
    public boolean hasTimeOfLastGET() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string timeOfLastGET = 7 [default = "0"];</code>
     */
    public java.lang.String getTimeOfLastGET() {
      java.lang.Object ref = timeOfLastGET_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeOfLastGET_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timeOfLastGET = 7 [default = "0"];</code>
     */
    public com.google.protobuf.ByteString
        getTimeOfLastGETBytes() {
      java.lang.Object ref = timeOfLastGET_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeOfLastGET_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
      prefixLength_ = 0;
      address_ = "";
      uploadNode_ = "";
      timeOfLastGET_ = "0";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPrivateKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrefixLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUploadNode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeOfLastGET()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, privateKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, publicKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, prefixLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAddressBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUploadNodeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTimeOfLastGETBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, privateKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, publicKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, prefixLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAddressBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUploadNodeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTimeOfLastGETBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static KeyRing.Key parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KeyRing.Key parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KeyRing.Key parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KeyRing.Key parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KeyRing.Key parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static KeyRing.Key parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static KeyRing.Key parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static KeyRing.Key parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static KeyRing.Key parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static KeyRing.Key parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(KeyRing.Key prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Key}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements KeyRing.KeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KeyRing.internal_static_Key_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KeyRing.internal_static_Key_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                KeyRing.Key.class, KeyRing.Key.Builder.class);
      }

      // Construct using KeyRing.Key.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        privateKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        prefixLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        uploadNode_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        timeOfLastGET_ = "0";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KeyRing.internal_static_Key_descriptor;
      }

      public KeyRing.Key getDefaultInstanceForType() {
        return KeyRing.Key.getDefaultInstance();
      }

      public KeyRing.Key build() {
        KeyRing.Key result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public KeyRing.Key buildPartial() {
        KeyRing.Key result = new KeyRing.Key(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.privateKey_ = privateKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.publicKey_ = publicKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.prefixLength_ = prefixLength_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.uploadNode_ = uploadNode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timeOfLastGET_ = timeOfLastGET_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof KeyRing.Key) {
          return mergeFrom((KeyRing.Key)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(KeyRing.Key other) {
        if (other == KeyRing.Key.getDefaultInstance()) return this;
        if (other.hasPrivateKey()) {
          setPrivateKey(other.getPrivateKey());
        }
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPrefixLength()) {
          setPrefixLength(other.getPrefixLength());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000010;
          address_ = other.address_;
          onChanged();
        }
        if (other.hasUploadNode()) {
          bitField0_ |= 0x00000020;
          uploadNode_ = other.uploadNode_;
          onChanged();
        }
        if (other.hasTimeOfLastGET()) {
          bitField0_ |= 0x00000040;
          timeOfLastGET_ = other.timeOfLastGET_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPrivateKey()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasPrefixLength()) {
          
          return false;
        }
        if (!hasUploadNode()) {
          
          return false;
        }
        if (!hasTimeOfLastGET()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        KeyRing.Key parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (KeyRing.Key) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes privateKey = 1;
      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes privateKey = 1;</code>
       */
      public boolean hasPrivateKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes privateKey = 1;</code>
       */
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <code>required bytes privateKey = 1;</code>
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes privateKey = 1;</code>
       */
      public Builder clearPrivateKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }

      // optional bytes publicKey = 2;
      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes publicKey = 2;</code>
       */
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes publicKey = 2;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>optional bytes publicKey = 2;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes publicKey = 2;</code>
       */
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      // required string name = 3;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      // required int32 prefixLength = 4;
      private int prefixLength_ ;
      /**
       * <code>required int32 prefixLength = 4;</code>
       */
      public boolean hasPrefixLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 prefixLength = 4;</code>
       */
      public int getPrefixLength() {
        return prefixLength_;
      }
      /**
       * <code>required int32 prefixLength = 4;</code>
       */
      public Builder setPrefixLength(int value) {
        bitField0_ |= 0x00000008;
        prefixLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 prefixLength = 4;</code>
       */
      public Builder clearPrefixLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prefixLength_ = 0;
        onChanged();
        return this;
      }

      // optional string address = 5;
      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 5;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        address_ = value;
        onChanged();
        return this;
      }

      // required string uploadNode = 6;
      private java.lang.Object uploadNode_ = "";
      /**
       * <code>required string uploadNode = 6;</code>
       */
      public boolean hasUploadNode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string uploadNode = 6;</code>
       */
      public java.lang.String getUploadNode() {
        java.lang.Object ref = uploadNode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uploadNode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uploadNode = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUploadNodeBytes() {
        java.lang.Object ref = uploadNode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uploadNode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uploadNode = 6;</code>
       */
      public Builder setUploadNode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        uploadNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uploadNode = 6;</code>
       */
      public Builder clearUploadNode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uploadNode_ = getDefaultInstance().getUploadNode();
        onChanged();
        return this;
      }
      /**
       * <code>required string uploadNode = 6;</code>
       */
      public Builder setUploadNodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        uploadNode_ = value;
        onChanged();
        return this;
      }

      // required string timeOfLastGET = 7 [default = "0"];
      private java.lang.Object timeOfLastGET_ = "0";
      /**
       * <code>required string timeOfLastGET = 7 [default = "0"];</code>
       */
      public boolean hasTimeOfLastGET() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string timeOfLastGET = 7 [default = "0"];</code>
       */
      public java.lang.String getTimeOfLastGET() {
        java.lang.Object ref = timeOfLastGET_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          timeOfLastGET_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timeOfLastGET = 7 [default = "0"];</code>
       */
      public com.google.protobuf.ByteString
          getTimeOfLastGETBytes() {
        java.lang.Object ref = timeOfLastGET_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeOfLastGET_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timeOfLastGET = 7 [default = "0"];</code>
       */
      public Builder setTimeOfLastGET(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        timeOfLastGET_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timeOfLastGET = 7 [default = "0"];</code>
       */
      public Builder clearTimeOfLastGET() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timeOfLastGET_ = getDefaultInstance().getTimeOfLastGET();
        onChanged();
        return this;
      }
      /**
       * <code>required string timeOfLastGET = 7 [default = "0"];</code>
       */
      public Builder setTimeOfLastGETBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        timeOfLastGET_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Key)
    }

    static {
      defaultInstance = new Key(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Key)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SavedKeys_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SavedKeys_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Key_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rKeyRing.proto\"\036\n\tSavedKeys\022\021\n\003key\030\001 \003(" +
      "\0132\004.Key\"\217\001\n\003Key\022\022\n\nprivateKey\030\001 \002(\014\022\021\n\tp" +
      "ublicKey\030\002 \001(\014\022\014\n\004name\030\003 \002(\t\022\024\n\014prefixLe" +
      "ngth\030\004 \002(\005\022\017\n\007address\030\005 \001(\t\022\022\n\nuploadNod" +
      "e\030\006 \002(\t\022\030\n\rtimeOfLastGET\030\007 \002(\t:\0010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SavedKeys_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SavedKeys_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SavedKeys_descriptor,
              new java.lang.String[] { "Key", });
          internal_static_Key_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Key_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Key_descriptor,
              new java.lang.String[] { "PrivateKey", "PublicKey", "Name", "PrefixLength", "Address", "UploadNode", "TimeOfLastGET", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
