// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payload.proto

package Messenger;

public final class Payload {
  private Payload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHAT = 1;</code>
     */
    CHAT(0, 1),
    /**
     * <code>EMAIL = 2;</code>
     */
    EMAIL(1, 2),
    /**
     * <code>CHATROOM = 3;</code>
     */
    CHATROOM(2, 3),
    ;

    /**
     * <code>CHAT = 1;</code>
     */
    public static final int CHAT_VALUE = 1;
    /**
     * <code>EMAIL = 2;</code>
     */
    public static final int EMAIL_VALUE = 2;
    /**
     * <code>CHATROOM = 3;</code>
     */
    public static final int CHATROOM_VALUE = 3;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 1: return CHAT;
        case 2: return EMAIL;
        case 3: return CHATROOM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Payload.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  public interface SignedPayloadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes serializedMessageData = 1;
    /**
     * <code>required bytes serializedMessageData = 1;</code>
     */
    boolean hasSerializedMessageData();
    /**
     * <code>required bytes serializedMessageData = 1;</code>
     */
    com.google.protobuf.ByteString getSerializedMessageData();

    // required bytes HMac = 5;
    /**
     * <code>required bytes HMac = 5;</code>
     */
    boolean hasHMac();
    /**
     * <code>required bytes HMac = 5;</code>
     */
    com.google.protobuf.ByteString getHMac();
  }
  /**
   * Protobuf type {@code SignedPayload}
   */
  public static final class SignedPayload extends
      com.google.protobuf.GeneratedMessage
      implements SignedPayloadOrBuilder {
    // Use SignedPayload.newBuilder() to construct.
    private SignedPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SignedPayload(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SignedPayload defaultInstance;
    public static SignedPayload getDefaultInstance() {
      return defaultInstance;
    }

    public SignedPayload getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SignedPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serializedMessageData_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000002;
              hMac_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Payload.internal_static_SignedPayload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Payload.internal_static_SignedPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Payload.SignedPayload.class, Payload.SignedPayload.Builder.class);
    }

    public static com.google.protobuf.Parser<SignedPayload> PARSER =
        new com.google.protobuf.AbstractParser<SignedPayload>() {
      public SignedPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignedPayload(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SignedPayload> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes serializedMessageData = 1;
    public static final int SERIALIZEDMESSAGEDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString serializedMessageData_;
    /**
     * <code>required bytes serializedMessageData = 1;</code>
     */
    public boolean hasSerializedMessageData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes serializedMessageData = 1;</code>
     */
    public com.google.protobuf.ByteString getSerializedMessageData() {
      return serializedMessageData_;
    }

    // required bytes HMac = 5;
    public static final int HMAC_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString hMac_;
    /**
     * <code>required bytes HMac = 5;</code>
     */
    public boolean hasHMac() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes HMac = 5;</code>
     */
    public com.google.protobuf.ByteString getHMac() {
      return hMac_;
    }

    private void initFields() {
      serializedMessageData_ = com.google.protobuf.ByteString.EMPTY;
      hMac_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSerializedMessageData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHMac()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, serializedMessageData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(5, hMac_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, serializedMessageData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, hMac_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Payload.SignedPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Payload.SignedPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Payload.SignedPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Payload.SignedPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Payload.SignedPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Payload.SignedPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Payload.SignedPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Payload.SignedPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Payload.SignedPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Payload.SignedPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Payload.SignedPayload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SignedPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Payload.SignedPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Payload.internal_static_SignedPayload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Payload.internal_static_SignedPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Payload.SignedPayload.class, Payload.SignedPayload.Builder.class);
      }

      // Construct using Payload.SignedPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serializedMessageData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        hMac_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Payload.internal_static_SignedPayload_descriptor;
      }

      public Payload.SignedPayload getDefaultInstanceForType() {
        return Payload.SignedPayload.getDefaultInstance();
      }

      public Payload.SignedPayload build() {
        Payload.SignedPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Payload.SignedPayload buildPartial() {
        Payload.SignedPayload result = new Payload.SignedPayload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serializedMessageData_ = serializedMessageData_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hMac_ = hMac_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Payload.SignedPayload) {
          return mergeFrom((Payload.SignedPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Payload.SignedPayload other) {
        if (other == Payload.SignedPayload.getDefaultInstance()) return this;
        if (other.hasSerializedMessageData()) {
          setSerializedMessageData(other.getSerializedMessageData());
        }
        if (other.hasHMac()) {
          setHMac(other.getHMac());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSerializedMessageData()) {
          
          return false;
        }
        if (!hasHMac()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Payload.SignedPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Payload.SignedPayload) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes serializedMessageData = 1;
      private com.google.protobuf.ByteString serializedMessageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes serializedMessageData = 1;</code>
       */
      public boolean hasSerializedMessageData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes serializedMessageData = 1;</code>
       */
      public com.google.protobuf.ByteString getSerializedMessageData() {
        return serializedMessageData_;
      }
      /**
       * <code>required bytes serializedMessageData = 1;</code>
       */
      public Builder setSerializedMessageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serializedMessageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes serializedMessageData = 1;</code>
       */
      public Builder clearSerializedMessageData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serializedMessageData_ = getDefaultInstance().getSerializedMessageData();
        onChanged();
        return this;
      }

      // required bytes HMac = 5;
      private com.google.protobuf.ByteString hMac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes HMac = 5;</code>
       */
      public boolean hasHMac() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes HMac = 5;</code>
       */
      public com.google.protobuf.ByteString getHMac() {
        return hMac_;
      }
      /**
       * <code>required bytes HMac = 5;</code>
       */
      public Builder setHMac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes HMac = 5;</code>
       */
      public Builder clearHMac() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hMac_ = getDefaultInstance().getHMac();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SignedPayload)
    }

    static {
      defaultInstance = new SignedPayload(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SignedPayload)
  }

  public interface MessageDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string senderAddress = 1;
    /**
     * <code>required string senderAddress = 1;</code>
     */
    boolean hasSenderAddress();
    /**
     * <code>required string senderAddress = 1;</code>
     */
    java.lang.String getSenderAddress();
    /**
     * <code>required string senderAddress = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenderAddressBytes();

    // required .MessageType messageType = 2;
    /**
     * <code>required .MessageType messageType = 2;</code>
     */
    boolean hasMessageType();
    /**
     * <code>required .MessageType messageType = 2;</code>
     */
    Payload.MessageType getMessageType();

    // required uint64 timeStamp = 3;
    /**
     * <code>required uint64 timeStamp = 3;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required uint64 timeStamp = 3;</code>
     */
    long getTimeStamp();

    // optional string subject = 4;
    /**
     * <code>optional string subject = 4;</code>
     */
    boolean hasSubject();
    /**
     * <code>optional string subject = 4;</code>
     */
    java.lang.String getSubject();
    /**
     * <code>optional string subject = 4;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    // required string UnencryptedMessage = 5;
    /**
     * <code>required string UnencryptedMessage = 5;</code>
     */
    boolean hasUnencryptedMessage();
    /**
     * <code>required string UnencryptedMessage = 5;</code>
     */
    java.lang.String getUnencryptedMessage();
    /**
     * <code>required string UnencryptedMessage = 5;</code>
     */
    com.google.protobuf.ByteString
        getUnencryptedMessageBytes();

    // required string name = 6;
    /**
     * <code>required string name = 6;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 6;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 6;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code MessageData}
   */
  public static final class MessageData extends
      com.google.protobuf.GeneratedMessage
      implements MessageDataOrBuilder {
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageData defaultInstance;
    public static MessageData getDefaultInstance() {
      return defaultInstance;
    }

    public MessageData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              senderAddress_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              Payload.MessageType value = Payload.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                messageType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStamp_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              subject_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              unencryptedMessage_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Payload.internal_static_MessageData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Payload.internal_static_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Payload.MessageData.class, Payload.MessageData.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageData> PARSER =
        new com.google.protobuf.AbstractParser<MessageData>() {
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string senderAddress = 1;
    public static final int SENDERADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object senderAddress_;
    /**
     * <code>required string senderAddress = 1;</code>
     */
    public boolean hasSenderAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string senderAddress = 1;</code>
     */
    public java.lang.String getSenderAddress() {
      java.lang.Object ref = senderAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string senderAddress = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderAddressBytes() {
      java.lang.Object ref = senderAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .MessageType messageType = 2;
    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private Payload.MessageType messageType_;
    /**
     * <code>required .MessageType messageType = 2;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .MessageType messageType = 2;</code>
     */
    public Payload.MessageType getMessageType() {
      return messageType_;
    }

    // required uint64 timeStamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timeStamp_;
    /**
     * <code>required uint64 timeStamp = 3;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 timeStamp = 3;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    // optional string subject = 4;
    public static final int SUBJECT_FIELD_NUMBER = 4;
    private java.lang.Object subject_;
    /**
     * <code>optional string subject = 4;</code>
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string subject = 4;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subject_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subject = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string UnencryptedMessage = 5;
    public static final int UNENCRYPTEDMESSAGE_FIELD_NUMBER = 5;
    private java.lang.Object unencryptedMessage_;
    /**
     * <code>required string UnencryptedMessage = 5;</code>
     */
    public boolean hasUnencryptedMessage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string UnencryptedMessage = 5;</code>
     */
    public java.lang.String getUnencryptedMessage() {
      java.lang.Object ref = unencryptedMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          unencryptedMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string UnencryptedMessage = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUnencryptedMessageBytes() {
      java.lang.Object ref = unencryptedMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unencryptedMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string name = 6;
    public static final int NAME_FIELD_NUMBER = 6;
    private java.lang.Object name_;
    /**
     * <code>required string name = 6;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string name = 6;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      senderAddress_ = "";
      messageType_ = Payload.MessageType.CHAT;
      timeStamp_ = 0L;
      subject_ = "";
      unencryptedMessage_ = "";
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSenderAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUnencryptedMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSenderAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, timeStamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUnencryptedMessageBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSenderAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timeStamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUnencryptedMessageBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Payload.MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Payload.MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Payload.MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Payload.MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Payload.MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Payload.MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Payload.MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Payload.MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Payload.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Payload.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Payload.MessageData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Payload.MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Payload.internal_static_MessageData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Payload.internal_static_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Payload.MessageData.class, Payload.MessageData.Builder.class);
      }

      // Construct using Payload.MessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        senderAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = Payload.MessageType.CHAT;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        subject_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        unencryptedMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Payload.internal_static_MessageData_descriptor;
      }

      public Payload.MessageData getDefaultInstanceForType() {
        return Payload.MessageData.getDefaultInstance();
      }

      public Payload.MessageData build() {
        Payload.MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Payload.MessageData buildPartial() {
        Payload.MessageData result = new Payload.MessageData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderAddress_ = senderAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.subject_ = subject_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.unencryptedMessage_ = unencryptedMessage_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Payload.MessageData) {
          return mergeFrom((Payload.MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Payload.MessageData other) {
        if (other == Payload.MessageData.getDefaultInstance()) return this;
        if (other.hasSenderAddress()) {
          bitField0_ |= 0x00000001;
          senderAddress_ = other.senderAddress_;
          onChanged();
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasSubject()) {
          bitField0_ |= 0x00000008;
          subject_ = other.subject_;
          onChanged();
        }
        if (other.hasUnencryptedMessage()) {
          bitField0_ |= 0x00000010;
          unencryptedMessage_ = other.unencryptedMessage_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000020;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSenderAddress()) {
          
          return false;
        }
        if (!hasMessageType()) {
          
          return false;
        }
        if (!hasTimeStamp()) {
          
          return false;
        }
        if (!hasUnencryptedMessage()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Payload.MessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Payload.MessageData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string senderAddress = 1;
      private java.lang.Object senderAddress_ = "";
      /**
       * <code>required string senderAddress = 1;</code>
       */
      public boolean hasSenderAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string senderAddress = 1;</code>
       */
      public java.lang.String getSenderAddress() {
        java.lang.Object ref = senderAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          senderAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string senderAddress = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenderAddressBytes() {
        java.lang.Object ref = senderAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string senderAddress = 1;</code>
       */
      public Builder setSenderAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senderAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string senderAddress = 1;</code>
       */
      public Builder clearSenderAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderAddress_ = getDefaultInstance().getSenderAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string senderAddress = 1;</code>
       */
      public Builder setSenderAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senderAddress_ = value;
        onChanged();
        return this;
      }

      // required .MessageType messageType = 2;
      private Payload.MessageType messageType_ = Payload.MessageType.CHAT;
      /**
       * <code>required .MessageType messageType = 2;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .MessageType messageType = 2;</code>
       */
      public Payload.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>required .MessageType messageType = 2;</code>
       */
      public Builder setMessageType(Payload.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MessageType messageType = 2;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = Payload.MessageType.CHAT;
        onChanged();
        return this;
      }

      // required uint64 timeStamp = 3;
      private long timeStamp_ ;
      /**
       * <code>required uint64 timeStamp = 3;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 timeStamp = 3;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required uint64 timeStamp = 3;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000004;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timeStamp = 3;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      // optional string subject = 4;
      private java.lang.Object subject_ = "";
      /**
       * <code>optional string subject = 4;</code>
       */
      public boolean hasSubject() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public Builder clearSubject() {
        bitField0_ = (bitField0_ & ~0x00000008);
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 4;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        subject_ = value;
        onChanged();
        return this;
      }

      // required string UnencryptedMessage = 5;
      private java.lang.Object unencryptedMessage_ = "";
      /**
       * <code>required string UnencryptedMessage = 5;</code>
       */
      public boolean hasUnencryptedMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string UnencryptedMessage = 5;</code>
       */
      public java.lang.String getUnencryptedMessage() {
        java.lang.Object ref = unencryptedMessage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          unencryptedMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string UnencryptedMessage = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUnencryptedMessageBytes() {
        java.lang.Object ref = unencryptedMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unencryptedMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string UnencryptedMessage = 5;</code>
       */
      public Builder setUnencryptedMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        unencryptedMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string UnencryptedMessage = 5;</code>
       */
      public Builder clearUnencryptedMessage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        unencryptedMessage_ = getDefaultInstance().getUnencryptedMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string UnencryptedMessage = 5;</code>
       */
      public Builder setUnencryptedMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        unencryptedMessage_ = value;
        onChanged();
        return this;
      }

      // required string name = 6;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 6;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string name = 6;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 6;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 6;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 6;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MessageData)
    }

    static {
      defaultInstance = new MessageData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MessageData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SignedPayload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SignedPayload_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPayload.proto\"<\n\rSignedPayload\022\035\n\025seri" +
      "alizedMessageData\030\001 \002(\014\022\014\n\004HMac\030\005 \002(\014\"\225\001" +
      "\n\013MessageData\022\025\n\rsenderAddress\030\001 \002(\t\022!\n\013" +
      "messageType\030\002 \002(\0162\014.MessageType\022\021\n\ttimeS" +
      "tamp\030\003 \002(\004\022\017\n\007subject\030\004 \001(\t\022\032\n\022Unencrypt" +
      "edMessage\030\005 \002(\t\022\014\n\004name\030\006 \002(\t*0\n\013Message" +
      "Type\022\010\n\004CHAT\020\001\022\t\n\005EMAIL\020\002\022\014\n\010CHATROOM\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SignedPayload_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SignedPayload_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SignedPayload_descriptor,
              new java.lang.String[] { "SerializedMessageData", "HMac", });
          internal_static_MessageData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MessageData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageData_descriptor,
              new java.lang.String[] { "SenderAddress", "MessageType", "TimeStamp", "Subject", "UnencryptedMessage", "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
